### ISSUE TITLE
Uncaught Error: %1 is not a valid Win32 application.

### ISSUE THREAD

**Issue by noradaiko** [Level/electron-demo#5]
Hi, I came from https://github.com/Level/leveldown/issues/239.
First, I got `DLL open failed when running with electron` error and rebuilding leveldown resolved it.
Next I got following error on my project and it occurred `electron-demo` as well:

```
Uncaught Error: %1 is not a valid Win32 application.
C:\Users\nora_000\Developments\electron-demo\node_modules\leveldown\build\Release\leveldown.node
```

My environment:
node: v4.1.1
Windows 8.1 64bit
Visual Studio 2013 Express

**Comment by noradaiko** [comment]
It was because the leveldown is built with `x64` arch and the electron process is `ia32`.

**Comment by francescoagati** [comment]
Hi there is a Solution For this pn Windows?
